[package]
name = "gitree"
version = "0.1.0"
authors = ["Vivien Maisonneuve <v.maisonneuve@gmail.com>"]
description = "Print a directory tree while respecting gitignore rules."
license = "MIT"
homepage = "https://gitlab.com/vmaison/gitree"
repository = "https://gitlab.com/vmaison/gitree.git"
readme = "README.md"
build = "build.rs"

[dependencies]
ansi_term = "0.11.0"
atty = "0.2.11"
clap = "2.32.0"
derive_more = "0.13.0"
ignore = "0.4.3"

[build-dependencies]
clap = "2.32.0"
